At the end of this experiment, you will be able to :

* Use Numpy Library

## Setup Steps

### 1. For the given array, display the elements which are greater than 20


In [3]:
import numpy as np

In [7]:
a = np.arange(36)
for i in a:
    if i>20:
        print(i)

21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


### 2. Create an array of 5 evenly spaced values from 0 to 20

In [8]:
# YOUR CODE HER 
np.linspace(0,20,5)


array([ 0.,  5., 10., 15., 20.])

### 3. Create an array with values ranging from 0 to 5 (inclusive) and reshape the array with 2 rows and 3 columns

In [11]:
a=np.arange(0,5)
a.reshape(2,3)


ValueError: cannot reshape array of size 5 into shape (2,3)

### 4. For a given 2-D array, perform vertical and horizontal stack

Hint: np.vstack, np.hstack

In [14]:
a = np.array([[9, 8],
              [6, 5]])

b = np.array([[4, 7],
              [3, 2]])

np.hstack(b)


array([4, 7, 3, 2])

### 5. For a given 2-D array, perform addition and subtraction on the given matrix

Hint: np.add, np.subtract

In [17]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

a+b


array([[ 6,  8],
       [10, 12]])

### 6. Matrix multiplication for 1-D array.

To multiply the matrix a and b

Hint: np.dot

In [18]:
a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])

a*b


array([81, 25, 28, 12])

### 7. Matrix multiplication for 2-D array.

To multiply the matrix a and b

Hint: np.dot

In [19]:
a = np.array([[1, 0],
             [0, 1]])

b = np.array([[4, 1],
              [2, 2]])

np.dot(a,b)


array([[4, 1],
       [2, 2]])

### 8. Solve the below equations using numpy solver

4X+3Y+2Z = 25,

-2X+2Y+3Z = -10,   

3X-5Y+2Z = -4

hint: np.linalg.solve


In [29]:
a=np.array([[4,3,2],[-1,2,3],[2,-5,2]])
b=np.array([25,-10,-4])
al =np.linalg.solve(a,b)
al


array([ 6.02941176,  2.11764706, -2.73529412])

### 9. For a given array, compute $e^x$ element-wise

In [31]:
a = np.array([3, 4, 6, 9, 8])

for i in a:
    print(np.exp(i))


20.085536923187668
54.598150033144236
403.4287934927351
8103.083927575384
2980.9579870417283


### 10. For a given array, find the cumulative sum of the elements row wise and column wise

In [34]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

np.sum(a)


66