In [21]:
!wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/social_advertising.csv

zsh:1: command not found: wget


In [22]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [23]:
df = pd.read_csv('../data_samples/Social_Network_Ads.csv')

In [24]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [25]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [26]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [27]:
df['Purchased'].unique()

array([0, 1])

In [28]:
df['Gender'] = df['Gender'].replace(['Male','Female'],[1,0])

/var/folders/56/t2yrw7yn6mbb21ng0n49wgdm0000gn/T/ipykernel_59699/3334265869.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace(['Male','Female'],[1,0])


In [29]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [30]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [31]:
x = df[['Gender', 'Age', 'EstimatedSalary']]
y = df['Purchased']

In [32]:
x

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 42)

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [35]:
x_train

array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.504

In [36]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train,y_train)  #memorising
y_pred = neigh.predict(x_test)
print('Accuracy Score ',accuracy_score(y_test,y_pred))

Accuracy Score  0.9125


In [37]:
for i in range(1,35):
  neigh = KNeighborsClassifier(n_neighbors=i)
  neigh.fit(x_train,y_train)  #memorising
  y_pred = neigh.predict(x_test)
  print('Accuracy Score ',i,accuracy_score(y_test,y_pred))

Accuracy Score  1 0.8875
Accuracy Score  2 0.8375
Accuracy Score  3 0.9125
Accuracy Score  4 0.9125
Accuracy Score  5 0.925
Accuracy Score  6 0.925
Accuracy Score  7 0.925
Accuracy Score  8 0.9375
Accuracy Score  9 0.9375
Accuracy Score  10 0.9375
Accuracy Score  11 0.9375
Accuracy Score  12 0.9375
Accuracy Score  13 0.9375
Accuracy Score  14 0.9375
Accuracy Score  15 0.9375
Accuracy Score  16 0.9375
Accuracy Score  17 0.9375
Accuracy Score  18 0.9375
Accuracy Score  19 0.9375
Accuracy Score  20 0.8625
Accuracy Score  21 0.875
Accuracy Score  22 0.875
Accuracy Score  23 0.875
Accuracy Score  24 0.8625
Accuracy Score  25 0.8625
Accuracy Score  26 0.8625
Accuracy Score  27 0.8625
Accuracy Score  28 0.8625
Accuracy Score  29 0.875
Accuracy Score  30 0.8625
Accuracy Score  31 0.8625
Accuracy Score  32 0.825
Accuracy Score  33 0.85
Accuracy Score  34 0.8375


In [38]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([('scaler',StandardScaler()),('knn',KNeighborsClassifier(n_neighbors=3))])

In [39]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [40]:
pipeline.predict([[1,24,19000]])

array([1])

In [41]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train,y_train)
y_pred = neigh.predict(x_test)
print('Accuracy Score ',accuracy_score(y_test,y_pred))

Accuracy Score  0.9125


In [42]:
x = df[['Gender', 'Age', 'EstimatedSalary']]
y = df['Purchased']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 42)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train,y_train)  #memorising
y_pred = neigh.predict(x_test)
print('Accuracy Score ',accuracy_score(y_test,y_pred))

Accuracy Score  0.9125


In [53]:
!pip install optuna

You should consider upgrading via the '/Users/udaykumar/Documents/workspace/understanding-gen-ai-ml/venv/bin/python3 -m pip install --upgrade pip' command.


In [44]:
import optuna
def objective(trial):
  k = trial.suggest_int('k',1,50)
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  accuracy = accuracy_score(y_test,y_pred)
  return accuracy
study = optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)
print(study.best_params)
print('Best Accuracy',study.best_value)

[I 2024-05-18 07:57:26,711] A new study created in memory with name: no-name-8ce73807-e93e-4a55-9125-f687aaad8a26
[I 2024-05-18 07:57:26,722] Trial 0 finished with value: 0.9375 and parameters: {'k': 18}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,728] Trial 1 finished with value: 0.9375 and parameters: {'k': 11}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,740] Trial 2 finished with value: 0.9375 and parameters: {'k': 18}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,749] Trial 3 finished with value: 0.825 and parameters: {'k': 32}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,762] Trial 4 finished with value: 0.8625 and parameters: {'k': 43}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,770] Trial 5 finished with value: 0.9375 and parameters: {'k': 17}. Best is trial 0 with value: 0.9375.
[I 2024-05-18 07:57:26,776] Trial 6 finished with value: 0.925 and parameters: {'k': 6}. Best is trial 0 with value: 0.9375.


{'k': 18}
Best Accuracy 0.9375
