<a href="https://colab.research.google.com/github/uday160386/ai_ml_exercises/blob/basic/Numpy_Exercises_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from array import *


In [7]:
a_colours = array('u',["b","g","o","p"])
print(a_colours)

array('u', 'bgop')


In [8]:
for i in a_colours:
  print(i)

b
g
o
p


In [20]:
print(len(a_colours))
print(a_colours[2])
a_colours.append('y')
print(a_colours)
print(a_colours.count('y'))
a_colours.pop()
print(a_colours)
print(a_colours.reverse())
print(a_colours.itemsize)
print(a_colours.typecode)

7
o
array('u', 'bgopyyyy')
4
array('u', 'bgopyyy')
None
4
u


# Multi-Dimensional Array

In [46]:
a_marks = array('i',[[78,69,55],[90,92,93],[75,58,46]])
print(len(a_marks))

TypeError: Field elements must be 2- or 3-tuples, got '[78, 69, 55]'

In [47]:
from numpy import *

a_marks = array([[78,69,55],[90,92,93],[75,58,46]])
print(a_marks)

[[78 69 55]
 [90 92 93]
 [75 58 46]]


In [30]:
print(a_marks.transpose())

[[78 90 75]
 [69 92 58]
 [55 93 46]]


In [41]:
import argparse
parser = argparse.ArgumentParser(description="Input multi dimential array")
parser.add_argument("n1",help="Enter 1st row elements")
parser.add_argument("n2",help="Enter 2nd row elements")
parser.add_argument("n3",help="Enter 3rd row elements")
args = parser.parse_args()

an_marray = array([args.n1,args.n2,args.n3])


usage: colab_kernel_launcher.py [-h] n1 n2 n3
colab_kernel_launcher.py: error: the following arguments are required: n2, n3


SystemExit: 2

In [42]:
a = arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [53]:
z = zeros(5,int)
o = ones(5, int)
print(o)
print(sum(a_marks))
print(max(a_marks))
print(min(a_marks))

[1 1 1 1 1]
656


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
a = array([1,2,3,0])
b = array([0,2,3,1])

c= a== b
print('result of a==b:  ', c)

result of a==b:   [False  True  True False]


In [55]:
print(a_marks.view())

[[78 69 55]
 [90 92 93]
 [75 58 46]]


In [56]:
b_marks = a_marks.copy()
print(b_marks)

[[78 69 55]
 [90 92 93]
 [75 58 46]]


In [59]:
print(a_marks.shape)
print(a_marks.size)
print(a_marks.itemsize)

(3, 3)
9
8


In [75]:
a_str = array([['uday','kumar','venkat'],['abhi','ram','venkata']])
print(a_str)
print('memory size :', a_str.itemsize)
print('memory size :', a_str.nbytes)

[['uday' 'kumar' 'venkat']
 ['abhi' 'ram' 'venkata']]
memory size : 28
memory size : 168


In [85]:
a_str = array([['uday','kumar','venkat'],['abhi','ram','venkata']])
print(a_str.reshape(3,2))
print(a_str.flatten())
a=eye(3)
print(a)
print(a_marks)

[['uday' 'kumar']
 ['venkat' 'abhi']
 ['ram' 'venkata']]
['uday' 'kumar' 'venkat' 'abhi' 'ram' 'venkata']
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[78 69 55]
 [90 92 93]
 [75 58 46]]


In [88]:
for i in range(len(a_marks)):
  for j in range(len(a_marks)):
    print("{} - {} - index of i &j is {}".format(i, j, a_marks[i][j]))

0 - 0 - index of i &j is 78
0 - 1 - index of i &j is 69
0 - 2 - index of i &j is 55
1 - 0 - index of i &j is 90
1 - 1 - index of i &j is 92
1 - 2 - index of i &j is 93
2 - 0 - index of i &j is 75
2 - 1 - index of i &j is 58
2 - 2 - index of i &j is 46


In [93]:
print(diagonal(a_marks))
print(a_marks.max())
print(a_marks.min())
print(a_marks.mean())
print(a_marks.sum())

[78 92 46]
93
46
72.88888888888889
656


In [94]:
print(sort(a_marks))

[[55 69 78]
 [90 92 93]
 [46 58 75]]


In [118]:
import random
print(random.randrange(100))


79
